[package]
name = "jdw-sequencer"
version = "0.1.0"
authors = ["Emstrevk <emil.strandvik@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] } # https://serde.rs/derive.html

rocket = "0.4.2"
chrono = "0.4.19"
bytes = "0.5.2"
futures = "0.3.1"
env_logger = "*"
log = "0.4"

reqwest = { version = "0.10", features = ["json", "blocking"] } # Added the blocking feature because async in threads is a mess
tracing = "0.1.5"
tracing-futures = "0.2.4"

serde_json = "1.0"
json = "*"

# Json deparsing library
[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]
